language: python

python:
  - 2.7
  - 3.3
  - 3.4

install:
  - sudo apt-get update
  - sudo apt-get install numpy astropy
  - pip install pytest

script:
  - sudo python setup.py install
  # TODO: run tests

